version: '3.8'
name: chinook
services:
  
  #----------------------------------------------------------------------------
  # DB2 Container
  # https://www.ibm.com/docs/en/db2/11.5?topic=system-macos
  # Commands:
  #   su - chinook
  #   db2 connect to Chinook
  #   db2 -tf /docker-entrypoint-initdb.d/create_database.sql
  #----------------------------------------------------------------------------
  db2:
    image: icr.io/db2_community/db2:latest
    platform: linux/amd64
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: chinook
      DB2INST1_PASSWORD: chinook
      DBNAME: Chinook
      BLU: false
      ENABLE_ORACLE_COMPATIBILITY: false
      UPDATEAVAIL: NO
      TO_CREATE_SAMPLEDB: false
      REPODB: false
      IS_OSXFS: true
      PERSISTENT_HOME: false
      HADR_ENABLED: false
    ports:
      - "50000:50000"
    volumes:
      - ./ChinookDatabase/DataSources/Chinook_Db2.sql:/scripts/Chinook_Db2.sql
    healthcheck:
      test: ["CMD", "su", "-", "chinook", "-c", "db2 connect to Chinook"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 120s
    command: >
      bash -c '
      /var/db2_setup/lib/setup_db2_instance.sh &
      until su - chinook -c "db2 connect to Chinook" > /dev/null 2>&1; do sleep 5; done;
      su - chinook -c "db2 connect to Chinook && db2 -tf /scripts/Chinook_Db2.sql";
      tail -f /dev/null
      '
  
  #----------------------------------------------------------------------------
  # MySQL Container
  # https://hub.docker.com/_/mysql
  # Commands:
  #   mysql -u chinook -p Chinook
  #----------------------------------------------------------------------------
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: chinook
      MYSQL_PASSWORD: chinook
      MYSQL_ROOT_PASSWORD: chinook
      MYSQL_DATABASE: Chinook
    ports:
      - "3306:3306"
    volumes:
      - ./ChinookDatabase/DataSources/Chinook_MySql.sql:/docker-entrypoint-initdb.d/Chinook_MySql.sql
      - ./ChinookDatabase/DataSources/Chinook_MySql_AutoIncrementPKs.sql:/docker-entrypoint-initdb.d/Chinook_MySql_AutoIncrementPKs.sql

  #----------------------------------------------------------------------------
  # Oracle Container
  # https://container-registry.oracle.com/ords/ocr/ba/database/express
  # https://hub.docker.com/r/gvenzl/oracle-xe (Apple M chips)
  # Commands:
  #   sqlplus -S / as sysdba @ /container-entrypoint-initdb.d/create_database.sql
  #----------------------------------------------------------------------------
  oracle:
    image: gvenzl/oracle-free:23-slim-faststart
    environment:
      ORACLE_PASSWORD: Test123!
      APP_USER: chinook
      APP_USER_PASSWORD: chinook
    ports:
      - "1521:1521"
    volumes:
      - ./ChinookDatabase/DataSources/Chinook_Oracle.sql:/container-entrypoint-initdb.d/create_database.sql

  #----------------------------------------------------------------------------
  # PostgreSQL Container
  # https://hub.docker.com/_/postgres
  # Commands:
  #   psql -U chinook chinook
  #----------------------------------------------------------------------------
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: chinook
      POSTGRES_PASSWORD: chinook
      POSTGRES_DB: chinook_db
    ports:
      - "5432:5432"
    volumes:
      - ./ChinookDatabase/DataSources/Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/Chinook_PostgreSql.sql
      - ./ChinookDatabase/DataSources/Chinook_PostgreSql_AutoIncrementPKs.sql:/docker-entrypoint-initdb.d/Chinook_PostgreSql_AutoIncrementPKs.sql
      - ./ChinookDatabase/DataSources/Chinook_PostgreSql_SerialPKs.sql:/docker-entrypoint-initdb.d/Chinook_PostgreSql_SerialPKs.sql

  #----------------------------------------------------------------------------
  # SQL Server Container
  # https://hub.docker.com/_/microsoft-mssql-server
  # Commands:
  #   /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -d master -i /docker-entrypoint-initdb.d/create_database.sql
  #   /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -d Chinook
  #----------------------------------------------------------------------------
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Test123!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - ./ChinookDatabase/DataSources/Chinook_SqlServer.sql:/scripts/Chinook_SqlServer.sql
      - ./ChinookDatabase/DataSources/Chinook_SqlServer_AutoIncrementPKs.sql:/scripts/Chinook_SqlServer_AutoIncrementPKs.sql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Test123!", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    command: >
      bash -c '
      /opt/mssql/bin/sqlservr &
      until /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -Q "SELECT 1" > /dev/null 2>&1; do sleep 2; done;
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -Q "CREATE DATABASE Chinook";
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -d Chinook -C -i /scripts/Chinook_SqlServer.sql;
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -Q "CREATE DATABASE Chinook_AutoIncrement";
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -d Chinook_AutoIncrement -C -i /scripts/Chinook_SqlServer_AutoIncrementPKs.sql;
      wait
      '
